routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
| ----------------------------------------------------------------------
|Rutas para controlador de bloques
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de los bloques
|
|
*/
Route::resource('bloques','BlockController');
Route::post('/ejecucion','BlockController@execute');
/*
| ----------------------------------------------------------------------
|Rutas para controlador de ayuda
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de ayuda
|
|
*/
Route::resource('introduccion','AyudaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('usuarios','UsuarioController'); 

Route::get('/search', 'UsuarioController@search');

Route::resource('proyectos','ProyectosController');
/*

| ----------------------------------------------------------------------
|Rutas para controlador de Roles
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de Roles
|
|
*/
Route::resource('Roles','RolesController');
Route::post('/Roles/store', 'RolesController@store');

/*Route::get('Roles',  function () {
    return "Probando";
});
*/

resources/views/usuarios/Editar.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')
<a href="{{ route('usuarios.index') }}" style="font-size:18px">
    <img src="http://localhost:8000/imagenes/back_icon.png" width="33">    Regresar</a>
    <br>
<p align="center"  style="font-size:47px">Editar Usuario</p>

<div class="container">
    <div class="row">
        <div class="col-sm-2" ></div>
        <div class="col-sm-8">
            <div class="card">
            <br>
                <div class="container">
                    <div class="row">
                        <div class="col-sm" style="background-color: #FB4D80"></div>
                        <div class="col-sm" style="background-color: #FFC32D"></div>
                        <div class="col-sm" style="background-color: #0C93CD"></div>
                    </div>
                    <div align="center">
                        <img src="http://localhost:8000/imagenes/UsuarioE.png" width="190">
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm" style="background-color: #FB4D80"></div>
                        <div class="col-sm" style="background-color: #FFC32D"></div>
                        <div class="col-sm" style="background-color: #0C93CD"></div>
                    </div>
                </div>
                <div class="container">
                    <form action="{{url('/usuarios/' . $user->id)}} " method="post">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                        <table>
                            <tbody>
                                <tr>
                                    <td >{{'Nombre: '}}</td>
                                    <td>
                                        <input type="text" name="name" id="Nombre" value="{{ $user->name}}">
                                    </td>
                                </tr>
                                <tr>
                                    <td>{{'Email:'}}</td>
                                    <td>
                                        <input type="text" name="email" id="Correo Correo Electronico" value="{{ $user->email}}">
                                    </td>
                                </tr>
                                <tr>
                                    <td>{{'Contraseña:'}}</td>
                                    <td>
                                        <input style="display: none" type="text" name="password" id="Password" value="{{ $user->password}}">
                                       <u><a href="{{ route('password.request') }}">{{('Restablecer contraseña')}}</a></u>
                                    </td>
                                </tr>
                                <tr>
                                    <td>{{'Rol de usuario:'}}</td>
                                    <td>
                                        <select name="roles">
                                            <?php $a="Definir rol"?>
                                            @foreach ($rolUser as $role)
                                                @if($role->user_id == $user->id)
                                                    @foreach ($roles as $rol)
                                                        @if($rol->id == $role->role_id)
                                                            <?php $a = $rol->name; ?>
                                                        @endif
                                                    @endforeach
                                                @endif
                                            @endforeach
                                            <option value="{{ $role['id']}}">{{$a}}</option>
                                            @foreach ($roles as $role)
                                                @if($role->name != $a)
                                                    <option value="{{ $role['id']}}">{{ $role['name']}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <br>
                        
                        <div align="center">
                            <button type="submit" class="btn light-blue accent-4 darken-4" style="font-size: 11px" a onclick="M.toast({html: 'Usuario actualizado con exito'})">
                                <i class="material-icons right">save</i>Guardar Cambios</button>
                        </div>
                    </form>
                    <br>
                </div>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>
<script>
  $(document).ready(function(){
    $('select').formSelect();
  });
</script>
@endsection

resources/views/usuarios/Usuarios.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="row">
    <div class="col">
        <h2 align="center" style="font-size:47px">Administración de Usuarios</h2>
    </div>
    <div class="w-100"></div>
    <div class="col"></div>
    <div class="col"></div>
    <div class="col">
        <form action="/search" method="get" style="background-color:; height:100px; padding: -10px 5px">
            <div class="card-body row no-gutters" >
                <div class="col-auto" style="padding: 35px 5px">
                    <button type="submit" style="background-color:transparent; border-color:transparent"><i class="material-icons">search</i></button>
                </div>
                <div class="col">
                    <br>
                    <input type="search" name="search" class="form-control" placeholder="Buscar por nombre">
                </div>
                <div class="col-auto" style="padding: 37px 5px">
                    <a href="{{ route('usuarios.index') }}">
                    <i class="material-icons" style="font-size: 20px; color:black">close</i></a>  
                </div> 
            </div>
        </form>
    </div>
    <div class="w-100"></div>
    <div class="col">
        <div class="card">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th width="10px">Código</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th colspan="3" width="5%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td style="padding: 20px 5px" HEIGHT="10">{{ $user->id }} </td> 
                        <td style="padding: 20px 5px"> <a href="{{ route('usuarios.show', $user->id) }}" style="color:black">{{ $user->name }} </a></td>
                        <td style="padding: 20px 5px"> <a href="{{ route('usuarios.show', $user->id) }}" style="color:black">{{ $user->email }} </a></td>
                    
                        <td style="padding: 20px 5px">
                            <a href="{{ '/usuarios/' .$user->id. '/edit'}}" style="background-color:transparent">
                                <img src="http://localhost:8000/imagenes/editt.png" alt="Editar" width="37">
                            </a>
                        </td>
                        <td>
                           <form action="{{ route('usuarios.destroy', $user->id)}}" method="POST">
                            {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                                <button onclick="return confirm('¿Estas seguro eliminar la cuenta? \n \nSi la eliminas no podrás revertir cambios \n')" 
                                    style="background-color:transparent; border-color:transparent"> <img src="http://localhost:8000/imagenes/delete.png" alt="Borrar" width="37"> </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm"></div>
            <div class="col-sm">{!! $users->render()  !!}</div>
            <div class="col-sm"></div>
            <div class="col-sm"></div>
        </div>
    </div>

    
</div>

@endsection

resources/views/usuarios/VerDetalle.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<a href="{{ route('usuarios.index') }}" style="font-size:18px">
    <img src="http://localhost:8000/imagenes/back_icon.png" width="35">    Regresar</a>
    <br>
<div class="container">
    <div class="row">
        <div class="col-sm-2" ></div>
        <div class="col-sm-7" align="center" >
            <p align="center"  style="font-size:47px">Perfil de Usuario</p>
            <div class="card">
            <br>
                <div class="container">
                    <div class="row">
                        <div class="col-sm" style="background-color: #FB4D80"></div>
                        <div class="col-sm" style="background-color: #FFC32D"></div>
                        <div class="col-sm" style="background-color: #0C93CD"></div>
                    </div>
                    <div>
                        <img src="http://localhost:8000/imagenes/Usuario.png" width="190">
                    </div>
                    <div class="card-content">
                        <p style="font-size:25px;">{{$user->name}}</p>

                        <?php $RolUsuario=""?>
                        @foreach ($rolUser as $role)
                            @if($role->user_id == $user->id)
                                @foreach ($roles as $rol)
                                    @if($rol->id == $role->role_id)
                                        <?php $RolUsuario = $rol->name; ?>
                                    @endif
                                @endforeach
                            @endif
                        @endforeach
                        {{$RolUsuario}}
                    </div>
                    <div class="row">
                        <div class="col-sm" style="background-color: #FB4D80"></div>
                        <div class="col-sm" style="background-color: #FFC32D"></div>
                        <div class="col-sm" style="background-color: #0C93CD"></div>
                    </div>
                </div>
                <div>
                    <div class="container" style="border-left: 3px solid #0C93CD">
                        <table class="table table-hover">
                            <tbody>
                                <tr>
                                    <td>Codigo: {{$user->id}}</td>
                                </tr>
                                <tr>
                                    <td>Email: {{$user->email}}</td>    
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="d-flex justify-content-center"> 
                        <a href="{{ route('usuarios.edit', $user->id) }}" class="btn light-blue accent-4 darken-4">
                            <i class="material-icons right">edit</i>Editar Datos</a>
                    </div>
                    <br>
                </div>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>
@endsection