routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
| ----------------------------------------------------------------------
|Rutas para controlador de bloques
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de los bloques
|
|
*/
Route::resource('bloques','BlockController');
Route::post('/ejecucion','BlockController@execute');
/*
| ----------------------------------------------------------------------
|Rutas para controlador de ayuda
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de ayuda
|
|
*/
Route::resource('introduccion','AyudaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('usuarios','UsuarioController'); 

Route::get('/search', 'UsuarioController@search');

Route::resource('proyectos','ProyectosController');
/*

| ----------------------------------------------------------------------
|Rutas para controlador de Roles
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de Roles
|
|
*/
Route::resource('Roles','RolesController');
Route::post('/Roles/store', 'RolesController@store');

/*Route::get('Roles',  function () {
    return "Probando";
});
*/

app/Role.php
<?php

namespace App;

use App\User;
use Illuminate\Notifications\Notifiable;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'description'
    ];

    protected $table ='roles';

    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }


}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Role;
use App\User;

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $request->user()->authorizeRoles([ 'Administrador']);

        $roles = DB::table('roles')
                ->orderBy('id', 'asc')
                ->get();
        return view('Roles.index', ['roles' => $roles]);
    }

   
    public function create()
    {
       return View('Roles.create'); 
    }

   
    public function store(Request $request)
    {
        $roles= new Role($request->all());
        $roles->save();
        return back()->with('Aviso','Rol creado con exito');  
    }

    public function show($id)
    {
        $roles = Role::find($id);
        return view('Roles.show', ['roles' => $roles]);
    }

    public function edit($id)
    {
        $roles=Role::all();
        $roles = $roles->find($id);
       /*  dd($roles);*/
        return view('Roles.edit', ['roles' => $roles]);
     }

    public function update(request $request, $id)
    {
       // dd($roles);
        $roles=Role::all();
        $roles = $roles->find($id);
        $roles->name = $request->name;
        $roles->description = $request->description; 
        $roles->save();
        return redirect()->route('Roles.index');
    }

    public function destroy($id)
    {
      $roles = Role::find($id);
      $roles->delete();
      return back()->with('Aviso','La rol fue eliminado con exito');  
    }
}

resources/views/Roles/create.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a href="{{ url ('/Roles') }}">
                       <i class="material-icons" style="font-size: 12px;">arrow_back_ios</i>Regresar</a>
                </div>
                <BR>
                <div class="card-body"> 
                    <div class="col-sm-16">
                        <h2>Crear Rol</h2>
                        <form action="/Roles" method="post">
                            {{ csrf_field() }}

                            <label for="Nombre">{{'Nombre del Rol'}}</label>
                            <input type="text" name="name" id="Nombre del Rol" >
                            <BR><BR>
                            
                            <BR><BR>
                            <label for="Descripcion">{{'Descripción del Rol'}}</label>
                            <input type="text" name="description" id="Descripción del Rol">
                            <BR><BR>
                                <div class="d-flex justify-content-center">
                                   <button type="submit" class="btn light-blue accent-4 darken-4" style="font-size: 11px" a onclick="M.toast({html: 'Rol creado con exito'})">
                                    <i class="material-icons right">save</i>Guardar Cambios</button>
                            </div>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 @endsection

resources/views/Roles/edit.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('Roles.index', $roles->id) }}">
                       <i class="material-icons" style="font-size: 12px;">arrow_back_ios</i>Regresar</a>
                </div>
                <BR>
                <div class="card-body"> 
                    <div class="col-sm-16">
                        <h2>Editar Información</h2>
                 
                        <form action="{{url('/Roles/' . $roles->id)}} " method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}


                            <label for="Nombre del rol">{{'Nombre del rol'}}</label>
                            <input type="text" name="name" id="Nombre del rol" value="{{ $roles->name}}">

                            <BR><BR>
                            <label for="Description">{{'Descripción'}}</label>
                            <input type="text" name="description" id="Description" value="{{ $roles->description}}">
                            <BR><BR>
                            
                                <div class="d-flex justify-content-center">
                                   <button type="submit" class="btn light-blue accent-4 darken-4" style="font-size: 11px" a onclick="M.toast({html: 'Usuario actualizado con exito'})">
                                    <i class="material-icons right">save</i>Guardar Cambios</button>
                            </div>
                      </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Roles/index.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="container" color="black">
    <div class="row justify-content-center">
        <div class="col-md-16">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-header">
                    <a href="{{ url ('/Roles/create') }}">
                       <i class="material-icons" style="font-size: 45px;">arrow_front_ios</i>Crear Rol</a>
                </div>
                <div class="card-body">
                        <h2 style="font-size: 50px">Administración de Roles</h2>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th width="10px">Código</th>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                    <th colspan="5" width="30%">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($roles as $role)
                                <tr>
                                    <td style="padding: 20px 5px">{{ $role->id }}</td>
                                    <td>{{ $role->name }}</td>
                                    <td>{{ $role->description }}</td>

                                 {{-- BOTONES --}}    
                                    <td style="padding: 12px 5px">
                                        <a href="{{ '/Roles/' .$role->id. '/edit'}} " class="btn light-blue accent-4 darken-4" style="font-size: 11px">Editar</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('Roles.destroy', $role->id)}}" method="POST">
                                        {{ csrf_field() }}
                                        {{method_field('DELETE')}}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button onclick="return confirm('¿Estas seguro eliminar la cuenta? \n \nSi lo eliminas no podrás revertir cambios \n')" 
                                                    class="btn light-blue accent-4 darken-4" style="font-size: 11px">Eliminar</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

 @endsection