routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
| ----------------------------------------------------------------------
|Rutas para controlador de bloques
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de los bloques
|
|
*/
Route::resource('bloques','BlockController');
Route::post('/ejecucion','BlockController@execute');
/*
| ----------------------------------------------------------------------
|Rutas para controlador de ayuda
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de ayuda
|
|
*/
Route::resource('introduccion','AyudaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('usuarios','UsuarioController'); 

Route::get('/search', 'UsuarioController@search');

Route::resource('proyectos','ProyectosController');
/*

| ----------------------------------------------------------------------
|Rutas para controlador de Roles
|_______________________________________________________________________
| Aqui definimos la ruta para el controlador de la vista de Roles
|
|
*/
Route::resource('Roles','RolesController');
Route::post('/Roles/store', 'RolesController@store');

/*Route::get('Roles',  function () {
    return "Probando";
});
*/

app/Proyectos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proyectos extends Model
{
    //
    protected $fillable = [
        'name','created', 'created_at','update_at','description','user_id','code',
    ];
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;
use App\Proyectos;
use Illuminate\Http\Request;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proyectos = Proyectos::orderBy('created','DESC')->paginate();
        return view('proyectos.Proyecto', compact('proyectos')); 
    }
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('proyectos.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $id=0;
        $i=1;

        Proyectos::create($request->all());
        $pro = Proyectos::orderBy('id','DESC')->paginate();
        
        foreach($pro as $item)
        {
            if($i =="1")
            {
                $id=$item->id;
                $i=$i+1;
            }
        }
        $proyecto= Proyectos::find($id);
        return view('bloques.index', compact('proyecto'));
        /**
        * $datosProyecto=request()->except('_token');
        * Proyectos::insert($datosProyecto);
        * return response()->json($datosProyecto);
        */
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $proyectos=Proyectos::find($id);
        return  view('proyectos.VerDetalle',compact('proyectos'));
 
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proyectos = Proyectos::find($id);
        return view('proyectos.edit', compact('proyectos'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $proyecto = Proyectos::find($id);
        
        $proyecto->code = $request->input('code');
        $proyecto->save();
        return redirect()->route('proyectos.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Proyectos::find($id)->delete();
        return back();
    }
}

resources/views/proyectos/Proyecto.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')
<h2 align="center">Mis Proyectos</h2>
<div class="btn-group">
    <a href="{{ route('proyectos.create') }}" class="btn light-blue accent-4 darken-4" >Nuevo Proyecto</a>
</div>
    <br></br>
    <?php $a = 0; ?>
    <?php $par = 0; ?>
    <div class="row">
        <div class="col s6">
        @foreach($proyectos as $proyecto)
            @if (Auth::user()->id == $proyecto->user_id)
            <?php $a++; ?> 
            @if($a%2 == 1)
             <div class="card">             
                <div class="card-image waves-effect waves-block waves-light">
                   <img class="activator" src="imagenes/imga.png" >
                </div>   
                <div class="card-content" width="10" >
                    <span class="card-title activator grey-text text-darken-4">{{ $proyecto->name }}<i class="material-icons right">more_vert</i></span>                      

                    <form action="{{ action('ProyectosController@destroy', $proyecto->id)}}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">
                    <button  onclick="return confirm('¿Eliminar proyecto?')"
                        style="background-color:transparent; border-color:transparent"> <img src="imagenes/elim.png" alt="Borrar" width="27">
                    </button> 
                        <a  href="{{action('ProyectosController@edit', $proyecto->id)}}"> | 
                            <img src="imagenes/editar.png" alt="Editar" width="27"></a>
                        <a  href="{{action('BlockController@show', $proyecto->id)}}"> | <img src="imagenes/codigo.png" alt="Bloques" width="27"></a>
                        <!-- a href=" {{action('ProyectosController@show', $proyecto->id)}}" class="btn light-blue accent-4 darken-4" style="font-size: 11px">Ver</a> -->
                 </form>  
                </div> 
                <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">{{ $proyecto->name }}<i class="material-icons right">close</i></span>
                <p>{{ $proyecto->description }}</p>
            </div>
                 
        </div>
                @endif
            @endif
        @endforeach
    </div>
        <div class="col s4">
        @foreach($proyectos as $proyecto)
            @if (Auth::user()->id == $proyecto->user_id)
                <?php $par++; ?> 
                @if($par%2 == 0)<div class="card">             
                <div class="card-image waves-effect waves-block waves-light" >
                   <img class="activator" src="imagenes/imga.png">
                </div>   
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{ $proyecto->name }}<i class="material-icons right">more_vert</i></span>                      
                    <form action="{{ action('ProyectosController@destroy', $proyecto->id)}}" method="POST">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                    <button  onclick="return confirm('¿Eliminar proyecto?')"
                        style="background-color:transparent; border-color:transparent"> <img src="imagenes/elim.png" alt="Borrar" width="27">
                    </button> 
                        <a  href="{{action('ProyectosController@edit', $proyecto->id)}}"> | 
                            <img src="imagenes/editar.png" alt="Editar" width="27"></a>
                        <a  href="{{action('BlockController@show', $proyecto->id)}}"> | <img src="imagenes/codigo.png" alt="Editar" width="27"></a>
                
                </div> 
                <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">{{ $proyecto->name }}<i class="material-icons right">close</i></span>
                <p>{{ $proyecto->description }}</p>
            </div>
                 
        </div>
                @endif
            @endif
        @endforeach
    </div> 
@endsection

resources/views/proyectos/VerDetalle.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">
                    <a href="{{ route('usuarios.index') }}">
                        <i class="material-icons" style="font-size: 12px;">arrow_back_ios</i>Regresar</a>
                </div>
                <div class="card-body">
                    <div class="col-sm-16" text>
                        <p style="font-size:20px;">
                            Nombre: {{$proyectos->name}}
                        </p>
                        <p style="font-size:20px;">
                            Codigo: {{$proyectos->id}}
                        </p>
                        <p style="font-size:20px;">
                            description: {{$proyectos->description}}
                        </p>
                        <p style="font-size:20px;">
                            created: {{$proyectos->created}}
                        </p>

                        <BR></BR>
                        <div class="d-flex justify-content-center"> 
                            <a href="{{ route('proyectos.edit', $proyectos->id) }}" class="btn light-blue accent-4 darken-4">
                                <i class="material-icons right">edit</i>Editar Datos</a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/proyectos/create.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')
<div class="container">
<div align="center" class="card-header">{{ __('Crear Proyecto') }}</div>

<div class="row" >
    <form method="POST" action="{{ route('proyectos.store') }}" role="form" class="col s12">
    {{ csrf_field() }}
      
      <div class="form-group row">
        <div class="input-field col s5">
            <input id="Nombre_proyecto" name="name" type="text" class="validate" required>
            <label for="Nombre_proyecto">Nombre del proyecto</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s5">
            <input id="descripcion" name="description" type="text" class="validate" required>
            <label for="descripcion">Descripción del proyecto</label>
        </div>
      </div>
      <div class="row">
					<div class="input-field col s5">
						<div class="form-group">
							<input style="display: none" type="datetime" name="created" id="created" class="form-control input-sm" value="<?php echo date("Y-m-d");?>">
						</div>
					</div>
					<div class="input-field col s5">
						<div class="form-group">
						  <input style="display: none" type="text" name="user_id" id="user_id" value="<?php echo Auth::user()->id?>" class="form-control input-sm">
						</div>
					</div>
			</div>
</div>
      <div class="form-group row mb-0">
      
            <div class=" col-md-6 offset-md-4 ">
                <a href="{{ route('proyectos.index') }}" class="btn light-blue accent-4 darken-4 ">
                <i class="material-icons" style="font-size: 12px; color:white;">arrow_back_ios</i>Regresar</a>
                <button type="submit" class="btn light-blue accent-4 darken-4" >
                        {{ __('Guardar') }}
                        <i class="material-icons right ">send</i> 
                </button> 
            </div>
        </div>
    </form>
  </div>
  </div>
  @endsection

resources/views/proyectos/edit.blade.php
@extends('layouts.introduccion')
@section('title','Programacion')
@extends('layouts.app')
@section('content')

<div class="container">
    <div align="center" class="card-header">{{ __('Editar proyecto') }}</div>
    <div class="row" >
        <form method="POST" action="{{url('/proyectos/' . $proyectos->id)}}" role="form" class="col s12">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
        
            <label for="Nombre">{{'Nombre'}}</label>
            <input type="text" name="name" id="Nombre" value="{{ $proyectos->name}}">

            <label for="description">{{'description'}}</label>
            <input type="text" name="description" id="description" value="{{ $proyectos->description}}">
            <BR><BR>
        
            <button  class="light-blue accent-4 darken-4"  >
                <a href="{{ route('proyectos.index') }}" class="btn light-blue accent-4 darken-4 ">
                <i class="material-icons" style="font-size: 12px; color:white;">arrow_back_ios</i>Regresar</a>
            </button>
            <button type="submit" class="btn light-blue accent-4 darken-4" style="font-size: 11px" a onclick="M.toast({html: 'Proyecto actualizado con exito'})">
                <i class="material-icons right">save</i>Guardar Cambios
            </button>
    
        </form>
    </div>
</div>
@endsection